# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20161215_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.TextField(),
        ),
    ]
